#pragma checksum "C:\Users\forti\Desktop\NEGRASM\Views\Contato\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "ee22ee2f5ddce298adcdf6bd6da321a2260bf5ad"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Contato_Index), @"mvc.1.0.view", @"/Views/Contato/Index.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\forti\Desktop\NEGRASM\Views\_ViewImports.cshtml"
using NEGRASM;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\forti\Desktop\NEGRASM\Views\_ViewImports.cshtml"
using NEGRASM.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"ee22ee2f5ddce298adcdf6bd6da321a2260bf5ad", @"/Views/Contato/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"f55df174fd64497c6481d1af370d09dbe917e444", @"/Views/_ViewImports.cshtml")]
    public class Views_Contato_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 1 "C:\Users\forti\Desktop\NEGRASM\Views\Contato\Index.cshtml"
  
    ViewData["Title"] = "Contato";

#line default
#line hidden
#nullable disable
            WriteLiteral(@"

    
  
        
           <div class=""row g-12 bg-light"" style=""background-image:url(https://i.pinimg.com/originals/84/87/e6/8487e680b07c2dc12f7cdb0f5883cfe0.jpg)"" width=""100"" height=""300"">

                <div class=""col-md-3 md-md-6 mt-4 p-md-4"">
                   <h4 class=""text-light"" >Fale Conosco</h4>
                   <br>
                   <br>
                   <h5 class=""text-light"" >Preencha os campos ao lado e deixe sua mensagem, se deseja ser um dos nossos parceiros deixe seu contato ou  a sua história se for selecionada poderá ser publicada.
                    desse formulário ao lado.</h5>
                </div>  
                <div class=""col-md-6 mb-md-8 p-md-4"">
                    <div class=""col-md-9 mt-4 p-md-4"">
                        <label  class=""text-light""  for=""exampleFormControlInput1"" class=""form-label"">Nome </label>
                        <input type=""name"" class=""form-control"" id=""exampleFormControlInput1"" placeholder=""Escreva seu nome"">
        ");
            WriteLiteral(@"            </div>
                    <div class=""col-md-9 mt-2 p-md-4"">
                        <label class=""text-light""  for=""exampleFormControlInput1"" class=""form-label"">Email </label>
                        <input type=""email"" class=""form-control"" id=""exampleFormControlInput1"" placeholder=""nome@exemplo.com"">
                    </div>
                  <div class=""col-md-12 mt-2 p-md-4"">
                      <label class=""text-light""  for=""exampleFormControlTextarea1"" class=""form-label"">Mensagem</label>
                       <textarea class=""form-control"" id=""exampleFormControlTextarea1"" rows=""3"" placeholder=""Digite aqui sua dúvidas, seu contato ou sua história...""></textarea>
                       <br>
                   </div>

                </div>
         </div> 

");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
